site_name: scMusketeers
theme: readthedocs
repo_url: git@github.com:AntoineCollin/scMusketeers.git
site_url: https://scMusketeers.readthedocs.io/

nav:
  - Home: "index.md"
  - Examples: "examples.md"
  - Contributing: "contributing.md"