site_name: sc_permut
theme: readthedocs
repo_url: https://github.com/becavin-lab/sc_permut
site_url: https://scpermut.readthedocs.io/

nav:
  - Home: "index.md"
  - Examples: "examples.md"
  - Contributing: "contributing.md"