site_name: scCerberus
theme: readthedocs
repo_url: https://github.com/AntoineCollin/scCerberus/
site_url: https://scCerberus.readthedocs.io/

nav:
  - Home: "index.md"
  - Examples: "examples.md"
  - Contributing: "contributing.md"