site_name: scMusketeers
theme: readthedocs
repo_url: https://github.com/AntoineCollin/scMusketeers
site_url: https://scMusketeers.readthedocs.io/

nav:
  - Home: "index.md"
  - Examples: "examples.md"
  - Contributing: "contributing.md"