---
workflow_ID: 5106
dataset:
  dataset_name: discovair_ajrccm_small
  class_key: celltype_lv2_V3
dataset_normalize:
  filter_min_counts: True
  normalize_size_factors: True
  scale_input: False
  logtrans_input: True
model_spec:
  model_name: dca_permuted
  ae_type: batch_removal
  hidden_size: (2000, 128, 64, 128, 2000)
  hidden_dropout: 0
  batchnorm: True
  activation: relu
  init: glorot_uniform
  batch_removal_weight: 0.2
model_training_spec:
  epochs: 100
  reduce_lr: 10
  early_stop: 25
  batch_size: 256
  optimizer: Adam
  verbose: True
  threads: None
  learning_rate: None
  n_perm: 1
  permute: True
  change_perm: True
  semi_sup: True
  unlabeled_category: nan
  save_zinb_param: False
  use_raw_as_output: False
  contrastive_margin : None
  same_class_pct : None
dataset_train_split:
  mode: percentage
  pct_split: None
  obs_key: None
  n_keep: 0.8
  split_strategy: random
  keep_obs: None
  train_test_random_seed: 200
  use_TEST : True
  obs_subsample: None
dataset_fake_annotation:
  make_fake: False
  true_celltype: None
  false_celltype: None
  pct_false: None
predictor_spec:
  predictor_model: MLP
  predict_key: celltype_lv2_V3
  predictor_hidden_sizes: 64
  predictor_epochs: 100
  predictor_batch_size: 64
  predictor_activation: softmax