---
workflow_ID: 5390
dataset:
  dataset_name: htap_final_C1_C5
  class_key: celltype
dataset_normalize:
  filter_min_counts: True
  normalize_size_factors: True
  scale_input: False
  logtrans_input: True
  use_hvg: None
model_spec:
  model_name: dca_permuted
  ae_type: normal
  hidden_size: (2000, 128, 64, 128, 2000)
  hidden_dropout: 0
  batchnorm: True
  activation: relu
  init: glorot_uniform
  batch_removal_weight: None
model_training_spec:
  epochs: 300
  reduce_lr: 10
  early_stop: 25
  batch_size: 256
  optimizer: Adam
  verbose: True
  threads: None
  learning_rate: None
  n_perm: 1
  permute: True
  change_perm: True
  semi_sup: False
  unlabeled_category: nan
  save_zinb_param: False
  use_raw_as_output: False
  contrastive_margin : None
  same_class_pct : None
dataset_train_split:
  mode: entire_condition
  pct_split: None
  obs_key: celltype_sample
  n_keep: None
  split_strategy: random
  keep_obs: ['AM1_C1', 'AM2_C1', 'ASMC_C1', 'AT1_C1', 'AT2a_C1', 'AT2b_C1', 'Adv.FB_C1', 'Alv.FB_C1', 'Basal_C1', 'Baso-Mast_C1', 'CD4.T_C1', 'CD8.T_C1', 'DC1_C1', 'DC2_C1', 'EMT_C1', 'EndoMT_C1', 'Lymph.EC_C1', 'MCC_C1', 'Monocytes_C1', 'NK_C1', 'Pericytes_C1', 'Pulm.Art.EC_C1', 'Pulm.Vein.EC_C1', 'Syst.Art.EC_C1', 'TRB-SC_C1', 'VSMC_C1', 'aCap.EC_C1', 'gCap.EC_C1', 'pre-TB-SC_C1', 'Secretory_C5']
  train_test_random_seed: 125
  use_TEST : True
  obs_subsample: None
dataset_fake_annotation:
  make_fake: False
  true_celltype: None
  false_celltype: None
  pct_false: None
predictor_spec:
  predictor_model: MLP
  predict_key: celltype
  predictor_hidden_sizes: 64
  predictor_epochs: 100
  predictor_batch_size: 64
  predictor_activation: softmax