---
workflow_ID: 11
dataset:
  dataset_name: ajrccm
  class_key: celltype
dataset_normalize:
  filter_min_counts: True
  normalize_size_factors: True
  scale_input: True
  logtrans_input: True
  use_hvg: None
model_spec:
  model_name: dca_permuted
  ae_type: zinb-conddisp
  hidden_size: 128
  hidden_dropout: 0
  batchnorm: True
  activation: relu
  init: glorot_uniform
  batch_removal_weight: None
model_training_spec:
  epochs: 20
  reduce_lr: 10
  early_stop: 5
  batch_size: 32
  optimizer: RMSprop
  verbose: True
  threads: None
  learning_rate: None
  n_perm: 1
  permute: True
  change_perm: False
  semi_sup: semi_sup
  unlabeled_category: NA
  save_zinb_param: NA
  use_raw_as_output: NA
  contrastive_margin : contrastive_margin
  same_class_pct : same_class_pct
dataset_train_split:
  mode: percentage
  pct_split: 0.99
  obs_key: None
  n_keep: None
  split_strategy: random
  keep_obs: None
  train_test_random_seed: 13
  use_TEST : False
  obs_subsample: None
dataset_fake_annotation:
  make_fake: False
  true_celltype: None
  false_celltype: None
  pct_false: None
predictor_spec:
  predictor_model: MLP
  predict_key: celltype
  predictor_hidden_sizes: 64
  predictor_epochs: 50
  predictor_batch_size: 32
  predictor_activation: NA