---
workflow_ID: 3919
dataset:
  dataset_name: pbmc3k_processed
  class_key: louvain
dataset_normalize:
  filter_min_counts: True
  normalize_size_factors: True
  scale_input: False
  logtrans_input: False
  use_hvg: None
model_spec:
  model_name: dca_permuted
  ae_type: normal
  hidden_size: 64
  hidden_dropout: 0.05
  batchnorm: True
  activation: tanh
  init: glorot_uniform
  batch_removal_weight: None
model_training_spec:
  epochs: 300
  reduce_lr: 10
  early_stop: 30
  batch_size: 64
  optimizer: Adam
  verbose: True
  threads: None
  learning_rate: None
  n_perm: 1
  permute: True
  change_perm: True
  semi_sup: semi_sup
  unlabeled_category: nan
  save_zinb_param: False
  use_raw_as_output: False
  contrastive_margin : contrastive_margin
  same_class_pct : same_class_pct
dataset_train_split:
  mode: percentage
  pct_split: 0.75
  obs_key: None
  n_keep: None
  split_strategy: random
  keep_obs: None
  train_test_random_seed: 89
  use_TEST : True
  obs_subsample: None
dataset_fake_annotation:
  make_fake: False
  true_celltype: None
  false_celltype: None
  pct_false: None
predictor_spec:
  predictor_model: MLP
  predict_key: louvain
  predictor_hidden_sizes: 16
  predictor_epochs: 100
  predictor_batch_size: 32
  predictor_activation: softmax